# Generated by Django 4.2.20 on 2025-04-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="Department",
            new_name="department",
        ),
    ]
