# Generated by Django 4.2.20 on 2025-04-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_studentexamresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentExamSummary",
            fields=[],
            options={
                "verbose_name": "Student Exam Summary",
                "verbose_name_plural": "Studetn Exam Summaries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exam.studentexamresult",),
        ),
    ]
