# Generated by Django 4.2.20 on 2025-04-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_delete_studentexamsummary_studentexamsummary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentexamsummary",
            options={
                "verbose_name": "Student Exam Summary",
                "verbose_name_plural": "Student Exam Summaries",
            },
        ),
        migrations.AddField(
            model_name="studentexamsummary",
            name="exam_results",
            field=models.ManyToManyField(
                blank=True, related_name="exam_summary", to="exam.studentexamresult"
            ),
        ),
    ]
