# Generated by Django 4.2.20 on 2025-04-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_alter_studentexamsummary_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentexamsummary",
            name="has_attempted",
            field=models.BooleanField(default=False),
        ),
    ]
