# Generated by Django 4.2.20 on 2025-05-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0007_studentexamsummary_has_attempted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "target_user",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("faculty", "Faculty"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
