# Generated by Django 4.2.20 on 2025-04-11 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faculty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=faculty.models.teacher_profile_upload_path,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "subject_specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=15, null=True)),
                ("experience_year", models.IntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
