# Generated by Django 4.2.20 on 2025-04-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="password",
            field=models.CharField(default=3398, max_length=128),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="teacher_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
