# Generated by Django 4.2.20 on 2025-04-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0003_alter_teacherprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="teacher_role",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
