# Generated by Django 4.2.20 on 2025-04-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0004_teacherprofile_teacher_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="email",
            field=models.EmailField(
                blank=True, default="default@clg.com", max_length=254, null=True
            ),
        ),
    ]
