# Generated by Django 4.2.20 on 2025-04-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0005_teacherprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
