# Generated by Django 4.2.20 on 2025-04-28 05:32

from django.db import migrations, models
import django.db.models.deletion
import faculty.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_department"),
        ("faculty", "0006_teacherprofile_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(upload_to=faculty.models.material_upload_path),
                ),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.department",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faculty.teacherprofile",
                    ),
                ),
            ],
        ),
    ]
