# Generated by Django 4.2.20 on 2025-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0007_teachermaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachermaterial",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
