# Generated by Django 4.2.20 on 2025-04-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0009_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="teacher_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("faculty", "Faculty"),
                    ("hod", "HOD"),
                    ("principal", "Principal"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                max_length=10,
            ),
        ),
    ]
