# Generated by Django 4.2.20 on 2025-04-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_studentprofile_samester"),
        ("faculty", "0011_attendance"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "lecture", "date")},
        ),
    ]
