# Generated by Django 4.2.20 on 2025-05-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0012_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
