# Generated by Django 4.2.20 on 2025-04-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_studentprofile_password_studentprofile_roll_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
