# Generated by Django 4.2.20 on 2025-04-11 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_department"),
        ("student", "0003_studentprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.department"
            ),
        ),
    ]
