# Generated by Django 4.2.20 on 2025-04-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_studentprofile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="samester",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
